# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('wordcloud', models.ImageField(default='bobross/media/default_cloud.png', upload_to='bobross/media/wordclouds/')),
                ('transcript', models.TextField()),
                ('transcript_file', models.FileField(upload_to='bobross/media/transcripts')),
                ('thumbnail', models.ImageField(default='bobross/media/default.png', upload_to='bobross/media/epi_thumbs')),
                ('yt_link', models.CharField(blank=True, default='', max_length=100)),
                ('yt_id', models.CharField(blank=True, default='', max_length=100)),
                ('painting', models.ImageField(default='bobross/media/default.png', upload_to='bobross/media/finished_paintings')),
                ('season', models.IntegerField()),
                ('episode_number', models.IntegerField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Paints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('amazon_link', models.CharField(max_length=100)),
                ('amazon_html', models.CharField(max_length=600)),
            ],
            options={
                'ordering': ('color',),
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='paints',
            field=models.ManyToManyField(to='bobross.Paints'),
        ),
    ]
