# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bobross', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting', models.ImageField(default='bobross/media/default.png', upload_to='bobross/media/user_paintings')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_paintings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
