# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobross', '0002_userart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userart',
            name='painting',
            field=models.CharField(max_length=100),
        ),
    ]
