# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobross', '0004_auto_20171109_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userart',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='epi_paintings', to='bobross.Episode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to=settings.AUTH_USER_MODEL),
        ),
    ]
