# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobross', '0005_auto_20171109_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userart',
            name='episode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='epi_paintings', to='bobross.Episode'),
        ),
        migrations.AlterField(
            model_name='userart',
            name='painting',
            field=models.ImageField(default='bobross/media/default.png', upload_to='user_paintings'),
        ),
    ]
