# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobross', '0006_auto_20171113_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userart',
            name='painting',
            field=models.ImageField(default='bobross/media/default.png', upload_to='bobross/media/user_paintings'),
        ),
    ]
