# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobross', '0007_auto_20171113_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('season', 'episode_number')},
        ),
        migrations.AlterField(
            model_name='userart',
            name='painting',
            field=models.ImageField(default='bobross/media/default.png', upload_to='user_paintings'),
        ),
    ]
